name = "rolldoradobonus-ch"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradobonus.ch"
HMAC_KEY = "486fdef0dd1cd77581f7a7b90d6ca4444499e4db40432655458ea917b315c450"
COOKIE_NAME = "19g"
PLAY_PATH = "try"
BUTTON_ID = "pc0d902b1a02f9b0bc8a0f897b69ccb6d"
GATE_SALT = "21d20c5e86b801e1"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0a9h"
CTA_SELECTOR = ".play-button"
