name = "rolldoradobonus-ch"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradobonus.ch"
HMAC_KEY = "486fdef0dd1cd77581f7a7b90d6ca4444499e4db40432655458ea917b315c450"
COOKIE_NAME = "evy"
PLAY_PATH = "join-now"
BUTTON_ID = "pc0d902b1a02f9b0bc8a0f897b69ccb6d"
GATE_SALT = "3b4a0e549a262b84"
